### ISSUE TITLE
Background color not correct when using a .desktop file or using kitty -e micro

### ISSUE THREAD

**Issue by Sininenblue** [catppuccin/micro#2]
I'm on Peppermint OS, with kitty as my terminal and I wanted to make a .desktop file for micro with the exec command
`exec=kitty -e micro`
but the background color doesn't match when I just use the micro command in the terminal

I'm pretty sure it has something to do with the MICRO_TRUECOLOR not working correctly because turning it off on my fish config file showed the same background color
But I don't exactly know how to fix that, or what exactly is going wrong

**Comment by elkrien** [comment]
> I'm on Peppermint OS, with kitty as my terminal and I wanted to make a .desktop file for micro with the exec command `exec=kitty -e micro` but the background color doesn't match when I just use the micro command in the terminal
> 
> I'm pretty sure it has something to do with the MICRO_TRUECOLOR not working correctly because turning it off on my fish config file showed the same background color But I don't exactly know how to fix that, or what exactly is going wrong

Try to use this command in desktop file:
exec=env MICRO_TRUECOLOR=1 kitty -e micro

**Comment by Sininenblue** [comment]
Sadly it still doesn't work and I'm not sure why, opening a new tab and using printenv I was able to confirm that the MICRO_TRUECOLOR was actually there

Seems like it's a micro thing

**Comment by elkrien** [comment]
> Sadly it still doesn't work and I'm not sure why, opening a new tab and using printenv I was able to confirm that the MICRO_TRUECOLOR was actually there
> 
> Seems like it's a micro thing

So, this is how my micro.desktop looks like:
```
#!/usr/bin/env xdg-open
[Desktop Entry]

Name=Micro
GenericName=Text Editor
Comment=Edit text files in a terminal

Icon=micro
Type=Application
Categories=Utility;TextEditor;Development;
Keywords=text;editor;syntax;terminal;

Terminal=false
MimeType=text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/xml;text/html;text/css;text/x-sql;text/x-diff;
```
and it looks fine:
![image](https://user-images.githubusercontent.com/78103450/174473783-0668fbff-b253-4f1c-96d5-863ebf9b218c.png)

When I use:
```Exec=kitty -e micro```
it looks like You described:
![image](https://user-images.githubusercontent.com/78103450/174473813-b51aaa1e-14c1-4633-a669-91ee70592e8c.png)

I also use fish where I have a line:
```export "MICRO_TRUECOLOR=1"```

I use Arch Linux. I will install Peppermint OS later in VM and will test.

**Comment by Sininenblue** [comment]
Thank you so much! It finally works. 

I'm not exactly sure what I did wrong the first time, since it seems like the exec command was the main thing that made it not work, but I was probably just being stupid
