### ISSUE TITLE
Comments are unreadable.

### ISSUE THREAD

**Issue by kulkesk** [catppuccin/micro#3]
Comments are too faint on my screen with Alacritty terminal. It's even worse with a smaller font. Barely readable
edit: this is a mocha theme

![image](https://github.com/catppuccin/micro/assets/72607301/98fb1db0-bdd0-4f85-86b6-d2e35a4476c5)

**Comment by elkrien** [comment]
To be honest I don't see an issue here. Colors are done within catppuccin palette and style guide. When I look at the screen You provided it is normally readable to me. Maybe it's the matter of Your monitor settings or its quality?

**Comment by sgoudham** [comment]
The style guide has since been updated to use `overlay2` which offers better contrast against `base` which is used for backgrounds.
